from django.conf.urls import patterns, url

urlpatterns = patterns('fitgoals.views',
    url(r'^$',
        'root_view',
        name='root_view'),
    url(r'^workouts/$',
        'workouts_view',
        name='workouts_view'),
    url(r'^events/$',
        'events_view',
        name='events_view'),
    url(r'^events/([0-9]+)/$',
        'event_year_view',
        name='event_year_view'),
    url(r'^events/([0-9]+)/([0-9]+)/$',
        'event_details_view',
        name='event_details_view'),
    url(r'^events/([0-9]+)/([0-9]+)/([0-9]+)/$',
        'event_join_or_leave_team',
        name='event_join_or_leave_team'),
    url(r'^events/([0-9]+)/([0-9]+)/(make-team)/$', # Next to fix up
        'event_make_team',
        name='event_make_team'),
    url(r'^leaderboards/$',
        'leaderboards_view',
        name='leaderboards_view'),
)